# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f4e8a6ad2651d76926608e5aee22602235a84195daae7086e90005a278c088605411642cda5f756a27c7acd53fe482f8e1060750530924659ac152580d93bf9

test:
  secret_key_base: 88f03591d4e9fa41ef3162734fb35ff7c2b573bfd25e515482b0a19cccf843a0ee7b301ef8fe301f64b22beb01706badd79c19858c4a0f7860544c022a1da0ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
